import type { BuildPlan, BuildPlanItem } from '../types';
import type { OutputFile } from '../../writer';

const RULE_PREFIX = 'ctxgraph--';
const MAX_RULE_BODY_CHARS = 12_000;
const MAX_DESCRIPTION_LEN = 120;

/** Strip YAML frontmatter from subsystem instruction markdown. */
export function stripInstructionFrontmatter(md: string): string {
  if (!md.startsWith('---')) return md.trim();
  const end = md.indexOf('\n---', 3);
  if (end === -1) return md.trim();
  const after = md.indexOf('\n', end + 4);
  return (after === -1 ? md.slice(end + 4) : md.slice(after + 1)).trim();
}

/** `applyTo` from plan → Cursor `globs` string (comma-separated). */
export function applyToToCursorGlobs(applyTo: string): string {
  const parts = applyTo
    .split(',')
    .map(s => s.trim())
    .filter(Boolean);
  if (parts.length === 0) return '**/*';
  return parts
    .map(p => p.replace(/\\/g, '/'))
    .join(', ');
}

export function slugFromInstructionFile(instructionRel: string): string {
  const base = instructionRel.replace(/\.instructions\.md$/i, '');
  const slug = base.replace(/[^a-zA-Z0-9]+/g, '-').replace(/^-+|-+$/g, '');
  const name = `${RULE_PREFIX}${slug || 'subsystem'}`;
  return name.length > 140 ? name.slice(0, 140) : name;
}

function escapeYamlString(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\r?\n/g, ' ');
}

function capRuleBody(body: string): string {
  if (body.length <= MAX_RULE_BODY_CHARS) return body;
  return (
    body.slice(0, MAX_RULE_BODY_CHARS - 80) +
    '\n\n…\n\n_(truncated — full graph in matching `.github/instructions/*.instructions.md`)_'
  );
}

export function buildCursorRuleMdc(
  planItem: BuildPlanItem,
  instructionRelPath: string,
  instructionBody: string
): string {
  const globs = applyToToCursorGlobs(planItem.applyTo);
  const desc = escapeYamlString(
    `${planItem.area} — ${planItem.applyTo}`.slice(0, MAX_DESCRIPTION_LEN)
  );
  const body = capRuleBody(stripInstructionFrontmatter(instructionBody));

  return [
    '---',
    `description: "${desc}"`,
    `globs: ${globs}`,
    'alwaysApply: false',
    '---',
    '',
    body,
    '',
    `<!-- context-graph: generated from \`.github/instructions/${instructionRelPath}\` -->`,
    `_Regenerate: \`context-graph build --no-llm\` · Do not hand-edit this rule._`,
  ].join('\n');
}

const RULES_README = `# Cursor rules (context-graph)

Files named \`ctxgraph--*.mdc\` are **auto-generated** from \`.github/instructions/*.instructions.md\`.

- **When you edit a file**, Cursor attaches the rule whose \`globs\` match that path.
- **Source of truth**: instruction files under \`.github/instructions/\`.
- **Router (always on)**: \`context-graph.mdc\`.

Regenerate after graph changes:

\`\`\`bash
context-graph build --no-llm
\`\`\`

Do not edit \`ctxgraph--*\` by hand — changes are overwritten on the next build.
`;

/**
 * Emit one \`.cursor/rules/ctxgraph--<slug>.mdc\` per subsystem so Cursor auto-loads
 * instructions without asking the model to open files manually.
 */
export function appendCursorRuleFiles(plan: BuildPlan, files: OutputFile[]): void {
  const writtenRulePaths: string[] = [];

  for (const s of plan.subsystems) {
    const instructionPath = `.github/instructions/${s.file}`;
    const inst = files.find(f => f.path === instructionPath);
    if (!inst?.content.trim()) continue;

    const slug = slugFromInstructionFile(s.file);
    const rulePath = `.cursor/rules/${slug}.mdc`;
    const mdc = buildCursorRuleMdc(s, s.file, inst.content);

    const existingIdx = files.findIndex(f => f.path === rulePath);
    if (existingIdx >= 0) files[existingIdx] = { path: rulePath, content: mdc };
    else files.push({ path: rulePath, content: mdc });

    writtenRulePaths.push(rulePath);
  }

  const manifest = [
    '# Generated by context-graph — one path per line',
    `# count: ${writtenRulePaths.length}`,
    ...writtenRulePaths.sort(),
    '',
  ].join('\n');

  const manifestPath = '.cursor/rules/.context-graph-manifest';
  const manifestIdx = files.findIndex(f => f.path === manifestPath);
  const manifestFile: OutputFile = { path: manifestPath, content: manifest };
  if (manifestIdx >= 0) files[manifestIdx] = manifestFile;
  else files.push(manifestFile);

  const readmePath = '.cursor/rules/README.context-graph.md';
  const readmeIdx = files.findIndex(f => f.path === readmePath);
  const readmeFile: OutputFile = { path: readmePath, content: RULES_README };
  if (readmeIdx >= 0) files[readmeIdx] = readmeFile;
  else files.push(readmeFile);
}
